apiVersion: v1
kind: ServiceAccount
metadata:
  name: browser-service
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: browser-service
rules:
  - apiGroups: ["selenosis.io"]
    resources: ["browsers"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: browser-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: browser-service
subjects:
- kind: ServiceAccount
  name: browser-service
  namespace: default
